repository = "https://github.com/ggml-org/llama.cpp.git"
commit = "002a12ad25503a93501b2e188c360029830a241a"
description = "v0.4.0-130-g002a12ad2"
sources = [
  "ggml/src/ggml-cuda/quantize.cu",
  "ggml/src/ggml-cuda/convert.cu",
  "ggml/src/ggml-cuda/mmvq.cu",
  "ggml/src/ggml-cuda/mmvf.cu",
  "ggml/src/ggml-cuda/mmf.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_1.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_2.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_3.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_4.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_5.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_6.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_7.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_8.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_9.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_10.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_11.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_12.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_13.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_14.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_15.cu",
  "ggml/src/ggml-cuda/template-instances/mmf-instance-ncols_16.cu",
  "ggml/src/ggml-cuda/mmq.cu",
  "ggml/src/ggml-cuda/mmid.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-mxfp4.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-nvfp4.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q1_0.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q2_0.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q4_0.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q4_1.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q5_0.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q5_1.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q8_0.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q2_k.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q3_k.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q4_k.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q5_k.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-q6_k.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq1_s.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq2_xxs.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq2_xs.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq2_s.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq3_xxs.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq3_s.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq4_nl.cu",
  "ggml/src/ggml-cuda/template-instances/mmq-instance-iq4_xs.cu",
]

headers = [
  "ggml/include/ggml-alloc.h",
  "ggml/include/ggml-backend.h",
  "ggml/include/ggml-cuda.h",
  "ggml/include/ggml.h",
  "ggml/include/gguf.h",
  "ggml/src/ggml-common.h",
  "ggml/src/ggml-impl.h",
  "ggml/src/ggml-cuda/common.cuh",
  "ggml/src/ggml-cuda/mma.cuh",
  "ggml/src/ggml-cuda/mmq-config-ampere.cuh",
  "ggml/src/ggml-cuda/mmq-config-blackwell.cuh",
  "ggml/src/ggml-cuda/mmq-config-cdna.cuh",
  "ggml/src/ggml-cuda/mmq-config-gcn.cuh",
  "ggml/src/ggml-cuda/mmq-config-pascal-dp4a.cuh",
  "ggml/src/ggml-cuda/mmq-config-pascal-older.cuh",
  "ggml/src/ggml-cuda/mmq-config-rdna2.cuh",
  "ggml/src/ggml-cuda/mmq-config-rdna3-5.cuh",
  "ggml/src/ggml-cuda/mmq-config-rdna3.cuh",
  "ggml/src/ggml-cuda/mmq-config-rdna4.cuh",
  "ggml/src/ggml-cuda/mmq-load-tiles.cuh",
  "ggml/src/ggml-cuda/mmq-vec-dot.cuh",
  "ggml/src/ggml-cuda/mmq.cuh",
  "ggml/src/ggml-cuda/mmid.cuh",
  "ggml/src/ggml-cuda/mmvq.cuh",
  "ggml/src/ggml-cuda/mmvf.cuh",
  "ggml/src/ggml-cuda/mmf.cuh",
  "ggml/src/ggml-cuda/quantize.cuh",
  "ggml/src/ggml-cuda/convert.cuh",
  "ggml/src/ggml-cuda/dequantize.cuh",
  "ggml/src/ggml-cuda/unary.cuh",
  "ggml/src/ggml-cuda/vecdotq.cuh",
  "ggml/src/ggml-cuda/vendors/cuda.h",
  "ggml/src/ggml-cuda/vendors/hip.h",
  "ggml/src/ggml-cuda/vendors/musa.h",
]
