# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from collections.abc import Mapping
from types import MappingProxyType

from vllm.logger import init_logger

from ..kernel_support import (
    IMATRIX_QUANT_TYPES,
    KQUANT_TYPES,
    STANDARD_QUANT_TYPES,
    TRITON_DEQUANT_TYPES,
    TRITON_MMQ_TYPES,
    TRITON_MMVQ_TYPES,
    UNQUANTIZED_TYPES,
)

logger = init_logger(__name__)


def is_layer_skipped_gguf(
    prefix: str,
    unquantized_modules: list[str],
    fused_mapping: Mapping[str, list[str]] = MappingProxyType({}),
):
    proj_name = prefix.split(".")[-1]
    if proj_name in fused_mapping:
        shard_prefixes = [
            prefix.replace(proj_name, shard_proj_name)
            for shard_proj_name in fused_mapping[proj_name]
        ]

        is_skipped = None
        for shard_prefix in shard_prefixes:
            is_shard_skipped = any(
                shard_prefix in module_name for module_name in unquantized_modules
            )

            if is_skipped is None:
                is_skipped = is_shard_skipped
            elif is_shard_skipped != is_skipped:
                raise ValueError(
                    f"Detected some but not all shards of {prefix} "
                    "are quantized. All shards of fused layers "
                    "to have the same precision."
                )
    else:
        is_skipped = any(module_name in prefix for module_name in unquantized_modules)

    assert is_skipped is not None
    return is_skipped


# Compatibility re-exports. The contents are generated by the centralized
# backend capability table in kernel_support.py; these names are retained so
# `vllm_gguf_plugin.quantization` can continue to expose them.
DEQUANT_TYPES = TRITON_DEQUANT_TYPES
MMVQ_QUANT_TYPES = TRITON_MMVQ_TYPES
MMQ_QUANT_TYPES = TRITON_MMQ_TYPES

__all__ = [
    "DEQUANT_TYPES",
    "IMATRIX_QUANT_TYPES",
    "KQUANT_TYPES",
    "MMQ_QUANT_TYPES",
    "MMVQ_QUANT_TYPES",
    "STANDARD_QUANT_TYPES",
    "UNQUANTIZED_TYPES",
]
